//Let create a Alphabet Object the has Spelling Audio,What is in the picture prounciation and picture

final Map alphabet = {
  'a': 'slide01',
  'b': 'slide02',
  'c': 'slide03',
  'd': 'slide04',
  'e': 'slide05',
  'f': 'slide06',
  'g': 'slide07',
  'h': 'slide08',
  'i': 'slide09',
  'j': 'slide10',
  'k': 'slide11',
  'l': 'slide12',
  'm': 'slide13',
  'n': 'slide14',
  'o': 'slide15',
  'p': 'slide16',
  'q': 'slide17',
  'r': 'slide18',
  's': 'slide19',
  't': 'slide20',
  'u': 'slide21',
  'v': 'slide22',
  'w': 'slide23',
  'x': 'slide24',
  'y': 'slide25',
  'z': 'slide26',
};
